source "https://rubygems.org"

gem "jekyll", "~> 3.3"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.8"
  gem "jekyll-sitemap", "~> 0.12"
  gem "jekyll-gist"
  gem "jekyll-paginate"
  gem "jekyll-theme-hyde"
end
