source "https://rubygems.org"

gem "jekyll", "~> 3.4"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-feed", "~> 0.9"
gem "jekyll-sitemap", "~> 1.0"
gem "jekyll-redirect-from", "~> 0.12"
gem "jekyll-optional-front-matter", "~> 0.1.2"
gem "jekyll-relative-links", "~> 0.4.0"
gem "jekyll-default-layout", "~> 0.1.4"
gem "jemoji", "~> 0.8.0"
gem "classifier-reborn"
