source "https://rubygems.org"
ruby "~> 2.0"
gem "jekyll", "~> 3.5"

gem "jekyll-avatar", "~> 0.5"
gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.9"
gem "jekyll-gist", "~> 1.4"
gem "jekyll-optional-front-matter", "~> 0.2"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-readme-index", "~> 0.1"
gem "jekyll-redirect-from", "~> 0.12"
gem "jekyll-relative-links", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.3"
gem "jekyll-sitemap", "~> 1.1"
gem "jekyll-titles-from-headings", "~> 0.4"
